[package]
name = "lite_cache"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
dashmap = "5.0"
once_cell = "1.18"
moka = { version = "0.12.8", features = ["future"] }
